# Generated by Django 3.2.10 on 2023-01-19 20:08

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bouquet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название букета')),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение букета')),
                ('description', models.TextField(verbose_name='Описание букета')),
                ('event', models.CharField(max_length=20, verbose_name='Событие')),
                ('price', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Цена')),
                ('is_recommended', models.BooleanField(default=False, verbose_name='Рекомендован')),
                ('height', models.CharField(max_length=120, verbose_name='Высота букета')),
                ('width', models.CharField(max_length=100, verbose_name='Ширина букета')),
            ],
            options={
                'verbose_name': 'Букет',
                'verbose_name_plural': 'Букеты',
            },
        ),
        migrations.CreateModel(
            name='Flower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название цветка')),
                ('price', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Цветок',
                'verbose_name_plural': 'Цветы',
            },
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя клиента')),
                ('phonenumber', phonenumber_field.modelfields.PhoneNumberField(db_index=True, max_length=128, region=None, verbose_name='Номер телефона')),
                ('status', models.CharField(choices=[('Raw', 'Не обработанный'), ('Processed', 'Обработанный')], default='Raw', max_length=50, verbose_name='Статус консультации')),
                ('source', models.CharField(choices=[('Site', 'Сайт'), ('WA', 'WhatsApp'), ('TG', 'Telegram'), ('Phonecall', 'Звонок')], default='Site', max_length=30, verbose_name='Откуда пришла заявка')),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес магазина')),
                ('phonenumber', phonenumber_field.modelfields.PhoneNumberField(db_index=True, max_length=128, region=None, verbose_name='Номер телефона')),
            ],
            options={
                'verbose_name': 'Магазин',
                'verbose_name_plural': 'Магазины',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(choices=[('FAST_AS_POSSIBLE', 'Как можно скорее'), ('FROM_10_TO_12', 'С 10:00 до 12:00'), ('FROM_12_TO_14', 'С 12:00 до 14:00'), ('FROM_14_TO_16', 'С 14:00 до 16:00'), ('FROM_16_TO_18', 'С 16:00 до 18:00'), ('FROM_18_TO_20', 'С 18:00 до 20:00')], max_length=30, verbose_name='Дата заказа')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата заказа')),
                ('customer_name', models.CharField(max_length=255, verbose_name='Имя клиента')),
                ('cost', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Стоимость')),
                ('phonenumber', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Номер телефона')),
                ('address', models.CharField(max_length=100, verbose_name='Адрес доставки')),
                ('bouquet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='Flower.bouquet', verbose_name='Букет')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='Bouquet_Flower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Количество')),
                ('bouquet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bouquet_flower', to='Flower.bouquet', verbose_name='Название букета')),
                ('flower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bouquet_flower', to='Flower.flower', verbose_name='Цветок в букете')),
            ],
            options={
                'verbose_name': 'Цветок в букете',
                'verbose_name_plural': 'Цветы в букете',
            },
        ),
    ]
