# Generated by Django 3.2.10 on 2023-01-18 09:15

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bouquet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='название букета')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Flower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='название цветка')),
                ('price', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='цена')),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='имя клиента')),
                ('number', models.CharField(max_length=11, verbose_name='номер клиента')),
                ('reason', models.CharField(max_length=255, verbose_name='причина')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='Дата заказа')),
                ('customer_name', models.CharField(max_length=255, verbose_name='Имя клиента')),
                ('number', models.CharField(max_length=11, verbose_name='номер клиента')),
                ('address', models.CharField(max_length=255, verbose_name='адрес')),
                ('cost', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='стоимость')),
                ('bouquet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='Flower.bouquet', verbose_name='букет')),
            ],
        ),
        migrations.CreateModel(
            name='Bouquet_Flower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='количество')),
                ('bouquet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bouquet_flower', to='Flower.bouquet', verbose_name='название букета')),
                ('flower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bouquet_flower', to='Flower.flower', verbose_name='цветок в букете')),
            ],
        ),
    ]
