# Generated by Django 3.2.10 on 2023-01-20 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Flower', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Occasion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Повод')),
            ],
        ),
        migrations.RemoveField(
            model_name='bouquet',
            name='event',
        ),
        migrations.AddField(
            model_name='bouquet',
            name='occasions',
            field=models.ManyToManyField(related_name='bouquets', to='Flower.Occasion', verbose_name='Для каких поводов'),
        ),
    ]
