# Generated by Django 3.2.10 on 2023-01-19 06:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Flower', '0002_auto_20230118_1810'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bouquet',
            options={'verbose_name': 'Букет', 'verbose_name_plural': 'Букеты'},
        ),
        migrations.AddField(
            model_name='bouquet',
            name='price',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Цена'),
        ),
    ]
