# Generated by Django 3.2.10 on 2023-01-19 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Flower', '0003_auto_20230119_0621'),
    ]

    operations = [
        migrations.AddField(
            model_name='bouquet',
            name='is_recommended',
            field=models.BooleanField(blank=True, null=True, verbose_name='Рекомендован'),
        ),
    ]
